name: CI/CD DÃ©ploiement

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Docker Login
      #   uses: docker/login-action@v2
      #   with:
      #     # username: ${{ secrets.DOCKER_USER }}
      #     # password: ${{ secrets.DOCKER_PASSWORD }}
      #     registry: https://registry.groupe5.com

      - name: Build Gitea Image
        run: docker build -t registry.groupe5.com/gitea:gitea-${{ github.sha }} .

      - name: Push Gitea Image
        run: docker push registry.groupe5.com/gitea:gitea-${{ github.sha }}

      # - name: Deploy Stack
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd ~/projetCloud
      #       docker compose pull
      #       docker compose up -d
